services:
  graph:
    image: binartist/deploybot
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    ports:
      - 8080:8080
    env_file:
      - ./.env
    restart: on-failure

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - .env
    volumes:
      - ./data:/data/db
